"""create agent tables

Revision ID: 4e97ff4fef89
Revises: 
Create Date: 2026-09-15 17:13:41.021547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e97ff4fef89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    # 阶段 1 只把扩展装上，**不建向量表**：
    # 华为云 BGE-M3 是 1024 维；过早把维度写死进表，二期换 embedding 模型就要迁移数据。
    # 这里 CREATE EXTENSION 零成本，还能提前暴露"镜像里没带 pgvector"这类环境问题。
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('agent_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 id'),
    sa.Column('message_uuid', sa.String(length=64), nullable=False, comment='消息唯一标识(uuid4.hex)'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属会话 id(agent_session.id)'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='角色:user/assistant/system/tool'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文(含 @docN 别名原文，不存文件正文/磁盘路径)'),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='附件引用[{alias,source_uuid,role,display_name}]'),
    sa.Column('intent', sa.String(length=16), nullable=True, comment='意图识别结果:chat/generate'),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='需求槽位(缺哪些槽位决定要不要继续澄清)'),
    sa.Column('is_memorable', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='是否值得进向量库(二期 RAG 用)'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('is_delete', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='是否删除:0否 1是'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_uuid')
    )
    op.create_index(op.f('ix_agent_message_session_id'), 'agent_message', ['session_id'], unique=False)
    op.create_table('agent_session',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 id'),
    sa.Column('session_uuid', sa.String(length=64), nullable=False, comment='会话唯一标识(uuid4.hex)'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属用户 id(MySQL user 表，跨库不 JOIN)'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='会话标题(取首条用户消息前若干字)'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False, comment='状态:active/archived'),
    sa.Column('current_stage', sa.String(length=16), nullable=True, comment='本会话最近一次生成的 Agent 阶段(取值同 agents/stages.py)'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='是否删除:0否 1是'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_index(op.f('ix_agent_session_user_id'), 'agent_session', ['user_id'], unique=False)
    op.create_table('generation_source',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 id'),
    sa.Column('source_uuid', sa.String(length=64), nullable=False, comment='源文件唯一标识(uuid4.hex)'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属用户 id(MySQL user 表，跨库不 JOIN)'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属会话 id(agent_session.id)'),
    sa.Column('alias', sa.String(length=32), nullable=False, comment='会话内别名(形如 @doc1)'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='原始文件名(只用于展示与宽松解析)'),
    sa.Column('mime', sa.String(length=128), nullable=True, comment='MIME 类型'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'content'"), nullable=False, comment='角色:content/style/both'),
    sa.Column('storage_path', sa.String(length=512), nullable=True, comment='落盘相对路径(uploads/{user_id}/...)'),
    sa.Column('parse_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False, comment='解析状态:pending/parsing/success/failed'),
    sa.Column('parse_error', sa.String(length=1024), nullable=True, comment='解析失败原因(如扫描版 PDF 无文本层)'),
    sa.Column('digest', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='解析出的需求摘要(RequirementDigest)'),
    sa.Column('is_indexed', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='是否已进向量库(二期 RAG 用)'),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('is_delete', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='是否删除:0否 1是'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'alias', name='uq_generation_source_session_alias'),
    sa.UniqueConstraint('source_uuid')
    )
    op.create_index(op.f('ix_generation_source_session_id'), 'generation_source', ['session_id'], unique=False)
    op.create_index(op.f('ix_generation_source_user_id'), 'generation_source', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_source_user_id'), table_name='generation_source')
    op.drop_index(op.f('ix_generation_source_session_id'), table_name='generation_source')
    op.drop_table('generation_source')
    op.drop_index(op.f('ix_agent_session_user_id'), table_name='agent_session')
    op.drop_table('agent_session')
    op.drop_index(op.f('ix_agent_message_session_id'), table_name='agent_message')
    op.drop_table('agent_message')
    # 刻意不 DROP EXTENSION vector：扩展是库级共享对象，可能已被其它表或后续迁移使用，
    # 跟着某个迁移一起删掉是危险的
    # ### end Alembic commands ###
