"""add draft requirement to agent session

Revision ID: eac80e932e7f
Revises: 4e97ff4fef89
Create Date: 2026-09-15 20:21:55.582928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eac80e932e7f'
down_revision: Union[str, Sequence[str], None] = '4e97ff4fef89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级到本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_session', sa.Column('draft_requirement', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='需求草稿(slots + 一句话摘要)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚本版本。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_session', 'draft_requirement')
    # ### end Alembic commands ###
